### ISSUE TITLE
Error with loading files in Jekyll

### ISSUE THREAD

**Issue by mlocher** [shipyard-framework/shipyard#1]
Upgrading to the latest version of Shipyard causes an error when running `jekyll build`. The error message is related to loading files:

> Dependency Error: Yikes! It looks like you don't have shipyard-framework or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- ../app/helpers/shipyard/button_helper' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

A quick look into the source suggests that the fix is to replace the `require` with `require_relative` in a couple of files.

**Comment by ryanjwilke** [comment]
This one is now fixed in https://github.com/shipyard-framework/shipyard/commit/4f3f0c0a14f18cc54b3201c02494e1042157c486
